# To use the MeowCop gem.
inherit_gem:
  meowcop:
    - config/rubocop.yml

# Load rubocop-rspec & rubocop-rails
require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: disable

### Lint

Lint/RaiseException:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false

Lint/DisjunctiveAssignmentInConstructor:
  Enabled: false

Lint/ErbNewArguments:
  Enabled: false

Lint/MissingCopEnableDirective:
  Enabled: false

Lint/Void:
  Enabled: false

Lint/UselessTimes:
  Enabled: false

Lint/UselessSetterCall:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

### Metrics

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

### Style

Style/AndOr:
  Enabled: true

Style/UnlessElse:
  Enabled: true

Style/RedundantReturn:
  Enabled: true

Style/RedundantSelf:
  Enabled: true

Style/RedundantBegin:
  Enabled: true

Style/ModuleFunction:
  Enabled: true

Style/RescueModifier:
  Enabled: true

Style/EmptyLiteral:
  Enabled: true

Style/MutableConstant:
  Enabled: true

### Naming

Naming/MethodName:
  Enabled: true

Naming/ConstantName:
  Enabled: true

### Rspec

RSpec/EmptyLineAfterExample:
  Enabled: false

RSpec/EmptyLineAfterExampleGroup:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/Focus:
  Enabled: false

RSpec/ImplicitExpect:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/ItBehavesLike:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/MessageExpectation:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/NotToNot:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false

RSpec/ReturnFromStub:
  Enabled: false

RSpec/SingleArgumentMessageChain:
  Enabled: false

RSpec/VariableName:
  Enabled: false

RSpec/VerifiedDoubleReference:
  Enabled: false
