# To use the MeowCop gem.
inherit_gem:
  meowcop:
    - config/rubocop.yml

Style/AndOr:
  Enabled: true

Style/UnlessElse:
  Enabled: true

Style/RedundantReturn:
  Enabled: true

Style/RedundantSelf:
  Enabled: true

Style/RedundantBegin:
  Enabled: true

Style/ModuleFunction:
  Enabled: true

Style/RescueModifier:
  Enabled: true

Style/EmptyLiteral:
  Enabled: true

Style/MutableConstant:
  Enabled: true

Layout/DotPosition:
  Enabled: true
  EnforcedStyle: leading

Lint/EnsureReturn:
  Enabled: true

Lint/RescueException:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Enabled: true

Lint/AmbiguousOperator:
  Enabled: true

Lint/AmbiguousRegexpLiteral:
  Enabled: true

Lint/AssignmentInCondition:
  Enabled: true

Lint/BooleanSymbol:
  Enabled: true

Lint/CircularArgumentReference:
  Enabled: true

Lint/DeprecatedClassMethods:
  Enabled: true

Lint/DisjunctiveAssignmentInConstructor:
  Enabled: true

Lint/DuplicateCaseCondition:
  Enabled: true

Lint/DuplicateHashKey:
  Enabled: true

Lint/DuplicateMethods:
  Enabled: true

Lint/EachWithObjectArgument:
  Enabled: true

Lint/ElseLayout:
  Enabled: true

Lint/EmptyEnsure:
  Enabled: true

Lint/EmptyExpression:
  Enabled: true

Lint/EmptyInterpolation:
  Enabled: true

Lint/FloatOutOfRange:
  Enabled: true

Lint/FormatParameterMismatch:
  Enabled: true

Lint/HeredocMethodCallPosition:
  Enabled: true

Lint/ImplicitStringConcatenation:
  Enabled: true

Lint/InheritException:
  Enabled: true

Layout/LineLength:
  Enabled: false

Naming/MethodName:
  Enabled: true

Naming/ConstantName:
  Enabled: true
